// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Y0HCiBYTbYK269uHpj3NbgUqhe8r6M4',
    appId: '1:385298524193:web:2cfadf9612698f40215b60',
    messagingSenderId: '385298524193',
    projectId: 'zdotcom',
    authDomain: 'zdotcom.firebaseapp.com',
    storageBucket: 'zdotcom.firebasestorage.app',
    measurementId: 'G-N1GH6YFH5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD453stpHhtFj6iGgYJDvSymEL5lF8M3mM',
    appId: '1:385298524193:android:7b4c43922fe75c3f215b60',
    messagingSenderId: '385298524193',
    projectId: 'zdotcom',
    storageBucket: 'zdotcom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfXyW_nBvzTELloZvCnskp1-fo0xXghWA',
    appId: '1:385298524193:ios:4706257fa6ac5b68215b60',
    messagingSenderId: '385298524193',
    projectId: 'zdotcom',
    storageBucket: 'zdotcom.firebasestorage.app',
    androidClientId: '385298524193-hgd8mtdkvmvkjc9ae2s2d5dnrucneq9s.apps.googleusercontent.com',
    iosClientId: '385298524193-8bremu8ucbhu3h7jkbl4atk4kkhm5fc6.apps.googleusercontent.com',
    iosBundleId: 'me.ritom.z.z',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfXyW_nBvzTELloZvCnskp1-fo0xXghWA',
    appId: '1:385298524193:ios:4706257fa6ac5b68215b60',
    messagingSenderId: '385298524193',
    projectId: 'zdotcom',
    storageBucket: 'zdotcom.firebasestorage.app',
    androidClientId: '385298524193-hgd8mtdkvmvkjc9ae2s2d5dnrucneq9s.apps.googleusercontent.com',
    iosClientId: '385298524193-8bremu8ucbhu3h7jkbl4atk4kkhm5fc6.apps.googleusercontent.com',
    iosBundleId: 'me.ritom.z.z',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5Y0HCiBYTbYK269uHpj3NbgUqhe8r6M4',
    appId: '1:385298524193:web:99e9a08256d0b579215b60',
    messagingSenderId: '385298524193',
    projectId: 'zdotcom',
    authDomain: 'zdotcom.firebaseapp.com',
    storageBucket: 'zdotcom.firebasestorage.app',
    measurementId: 'G-BYRL9295SZ',
  );

}